# -*- coding: utf-8 -*-
"""vit Project Model train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yr8leqUg2QEWJPUA4aDfpZ84SR7dEk4s

# Crack and Pothole Detection with YOLOv8
This notebook demonstrates how to train a YOLOv8 model on a combined dataset (Cracks and Potholes) to detect both on any image. We will use Roboflow to download a merged dataset and Ultralytics to train it.
"""

!pip install ultralytics roboflow

"""## 1. Import Libraries"""

import os
from ultralytics import YOLO
from IPython.display import Image, display

"""## 2. Prepare the Dataset
To detect **both cracks and potholes**, we need a dataset containing both classes.
"""

from roboflow import Roboflow
rf = Roboflow(api_key="S5BEx5bN53CGMNOYB9of")
project = rf.workspace("smark-z7pr6").project("road-potholes-and-cracks-jmxtp")
version = project.version(6)
dataset = version.download("yolov8")
data_yaml_path = f"{dataset.location}/data.yaml"

"""## 3. Train the YOLOv8 Model
Now we will train the YOLOv8 model on our combined dataset. This ensures the model learns both 'crack' and 'pothole' classes.
"""

model = YOLO("yolov8s.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(
    data=data_yaml_path,
    epochs=30,
    imgsz=640,
    batch=16,
    name="yolov8n_cracks_and_potholes",
    amp=False
)

"""## 4. Run Inference on a Test Image
Upload an image containing both a crack and a pothole to see the results.
"""

from google.colab import files
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

best_model = YOLO('/content/runs/detect/yolov8n_cracks_and_potholes/weights/best.pt')

results = best_model.predict(source=image_path, conf=0.10, save=True, name='my_detection')

result_path = f"runs/detect/my_detection/{image_path}"

# Look at the first image result
result = results[0]

# Loop through every box detected in the image
for box in result.boxes:
    class_id = int(box.cls[0])
    class_name = result.names[class_id]

    # Get the width and height of the box in pixels
    width = int(box.xywh[0][2])
    height = int(box.xywh[0][3])

    print(f"Detected {class_name}: Width = {width}px, Height = {height}px")

# 1. First, measure or estimate how many pixels wide the entire road lane is in your picture
lane_width_pixels = 1000  # Example: The road is 1000 pixels wide in the image
lane_width_meters = 3.5   # Example: A standard road is 3.5 meters wide

# Calculate your conversion ratio (how many meters is 1 pixel?)
meters_per_pixel = lane_width_meters / lane_width_pixels

# 2. Look at the YOLO results and convert them!
result = results[0]

for box in result.boxes:
    # Get the class name (Crack vs Pothole)
    class_id = int(box.cls[0])
    class_name = result.names[class_id]

    # Get the width and height of the box in pixels
    width_px = int(box.xywh[0][2])
    height_px = int(box.xywh[0][3])

    # Do the math to convert to METERS!
    width_m = width_px * meters_per_pixel
    height_m = height_px * meters_per_pixel

    # Print the result rounded to 2 decimal places
    print(f"Detected {class_name}: {width_m:.2f} meters wide, {height_m:.2f} meters long")

import numpy as np
from PIL import Image as PILImage # Renamed to avoid clash with IPython.display.Image
from IPython.display import display, Image
from io import BytesIO

# Check if results object is not empty
if results:
    # Get the plotted image (numpy array) from the first result
    im_array = results[0].plot()

    # Convert the numpy array to a PIL Image.
    # YOLO's plot() often returns BGR, so we reverse the channels to get RGB for PIL.
    im = PILImage.fromarray(im_array[..., ::-1])

    # To display the PIL Image in Colab without saving to a file,
    # we can save it to a BytesIO object and then display it using IPython.display.Image
    buffer = BytesIO()
    im.save(buffer, format="JPEG") # You can choose other formats like PNG
    display(Image(data=buffer.getvalue()))
else:
    print("No results to display. The prediction might have failed or returned an empty result.")

# best_model = YOLO('/content/runs/detect/yolov8n_cracks_and_potholes/weights/best.pt')

# results = best_model.predict(source=image_path, conf=0.25, save=True, name='my_detection')

# result_path = f"runs/detect/my_detection/{image_path}"
# display(Image(filename=result_path))

"""## 5. Validate the Model
Check the accuracy of the dual-detection model.
"""

metrics = best_model.val()
print(f"Mean Average Precision (mAP@0.5:0.95): {metrics.box.map}")

"""## 6. Export / Save the Model
You can export the model back as a pickle file if needed.
"""

import torch

# import torch

# # save model weights
# torch.save(model.state_dict(), "model.pth")

# from google.colab import files

# # This is the pure PyTorch file YOLOv8 automatically created for you during training!
# pytorch_model_path = '/content/runs/detect/yolov8n_cracks_and_potholes/weights/best.pt'

# # Download the PyTorch file to your computer
# files.download(pytorch_model_path)

with open('my_pothole_crack_detector.pkl', 'wb') as f:
    pickle.dump(best_model, f)
# You can alternatively download the best.pt file directly:
# files.download('/content/runs/detect/yolov8n_cracks_and_potholes/weights/best.pt')