# -*- coding: utf-8 -*-
"""Vit ProjectPredtict images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nT8o5CL9YhwhkDCeF0LoHP9q5cyUet1m
"""

# # 1. Install the ultralytics library if you haven't already
# !pip install ultralytics

# from google.colab import files
# from IPython.display import Image, display
# from ultralytics import YOLO

# # 2. Upload your best.pt file
# print("Step 1: Upload your 'best.pt' file")
# model_uploaded = files.upload()
# model_path = list(model_uploaded.keys())[0]

# # 3. Upload your test image
# print("\nStep 2: Upload a road image to test")
# img_uploaded = files.upload()
# image_path = list(img_uploaded.keys())[0]

# # 4. Load the custom YOLO model
# print("\nLoading model and predicting...")
# model = YOLO(model_path)

# # 5. Run inference to detect cracks and potholes
# # `save=True` will tell YOLO to draw the boxes and save the image
# results = model.predict(source=image_path, conf=0.25, save=True)

# # 6. Display the result inline in the Colab notebook
# # YOLO saves outputs in runs/detect/predict/
# save_dir = results[0].save_dir
# result_image_path = f"{save_dir}/{image_path}"

# display(Image(filename=result_image_path))

# 1. Install the ultralytics library if you haven't already
!pip install ultralytics

from google.colab import files
from IPython.display import Image, display
from ultralytics import YOLO

# 2. Upload your best.pt file
print("Step 1: Upload your 'best.pt' file")
model_uploaded = files.upload()
model_path = list(model_uploaded.keys())[0]

# 3. Upload your test image
print("\nStep 2: Upload a road image to test")
img_uploaded = files.upload()
image_path = list(img_uploaded.keys())[0]

# 4. Load the custom YOLO model
print("\nLoading model and predicting...")
model = YOLO(model_path)

# 5. Run inference to detect cracks and potholes
# `save=True` will tell YOLO to draw the boxes and save the image
results = model.predict(source=image_path, conf=0.10, save=True)

# 6. Display the result inline in the Colab notebook
# YOLO saves outputs in runs/detect/predict/
save_dir = results[0].save_dir
result_image_path = f"{save_dir}/{image_path}"

display(Image(filename=result_image_path))

# 6. Display the result inline in the Colab notebook
# YOLO saves outputs in runs/detect/predict/
import numpy as np
from PIL import Image as PILImage # Renamed to avoid clash with IPython.display.Image
from IPython.display import display, Image
from io import BytesIO

# Check if results object is not empty
if results:
    # Get the plotted image (numpy array) from the first result
    im_array = results[0].plot()

    # Convert the numpy array to a PIL Image.
    # YOLO's plot() often returns BGR, so we reverse the channels to get RGB for PIL.
    im = PILImage.fromarray(im_array[..., ::-1])

    # To display the PIL Image in Colab without saving to a file,
    # we can save it to a BytesIO object and then display it using IPython.display.Image
    buffer = BytesIO()
    im.save(buffer, format="JPEG") # You can choose other formats like PNG
    display(Image(data=buffer.getvalue()))
else:
    print("No results to display. The prediction might have failed or returned an empty result.")

# Look at the first image result
result = results[0]

# Loop through every box detected in the image
for box in result.boxes:
    class_id = int(box.cls[0])
    class_name = result.names[class_id]

    # Get the width and height of the box in pixels
    width = int(box.xywh[0][2])
    height = int(box.xywh[0][3])

    print(f"Detected {class_name}: Width = {width}px, Height = {height}px")

# 1. First, measure or estimate how many pixels wide the entire road lane is in your picture
lane_width_pixels = 1000  # Example: The road is 1000 pixels wide in the image
lane_width_meters = 3.5   # Example: A standard road is 3.5 meters wide

# Calculate your conversion ratio (how many meters is 1 pixel?)
meters_per_pixel = lane_width_meters / lane_width_pixels

# 2. Look at the YOLO results and convert them!
result = results[0]

for box in result.boxes:
    # Get the class name (Crack vs Pothole)
    class_id = int(box.cls[0])
    class_name = result.names[class_id]

    # Get the width and height of the box in pixels
    width_px = int(box.xywh[0][2])
    height_px = int(box.xywh[0][3])

    # Do the math to convert to METERS!
    width_m = width_px * meters_per_pixel
    height_m = height_px * meters_per_pixel

    # Print the result rounded to 2 decimal places
    print(f"Detected {class_name}: {width_m:.2f} meters wide, {height_m:.2f} meters long")

